sudo: requried

services:
  - docker

before_install:
  - docker -v
  - docker-compose -v

install:
  - ./get-byfn.sh
  - ./get-docker-images.sh

script:
  - pwd
  - ls -l
  - cd first-network
  - echo "----E2E Starts----"
  - ./byfn up

after_script:
  - ./byfn down  